### ISSUE TITLE
Free parameters on gates

### ISSUE THREAD

**Issue by obriente** [brianzi/quantumsim#27] opened 2018-01-26 11:28 UTC
For many applications we need to run the same circuit many times but with a small number of rotations adjusted (e.g. VQE/QPE). It would be more efficient and a lot cleaner if we can do this directly to the gate rather than having to rebuild the entire circuit.

In the current scheme, this is fairly easy - I'm just going to write an update function within the rotation gate classes that takes a new angle and inserts it directly into the PTM. But I'm not sure how well this will work with the compilation methods that are coming in quantumsim v2. My suggestion would be to assign gates that will need adjusting a 'do not compile' flag that prevents them from being pushed together into a larger operation. Does this seem like a good idea?

If this is going to be a big issue to implement, I'll do some timing analysis of creating vs applying circuits to make sure it provides a significant speedup compared to just remaking the circuit every time something needs changing.

**Comment by brianzi** [comment] 2018-01-26 14:14
duplicate of #5

**Closed by brianzi** 2018-01-26 14:14 UTC
